"""Initial migration.

Revision ID: 34992ce8ec07
Revises: 
Create Date: 2024-11-14 17:55:28.305796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34992ce8ec07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base')
    # ### end Alembic commands ###
